export interface LibSection {
  id: string;
  label: string;
}

export type LibCategory = "ml" | "dl";

export interface Library {
  slug: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  category: LibCategory;
  sections: LibSection[];
}

export const LIBRARIES: Library[] = [
  {
    slug: "numpy",
    title: "NumPy",
    description: "배열 생성 · 수학/선형대수 · 난수",
    icon: "⬡",
    color: "#4878D0",
    category: "ml",
    sections: [
      { id: "import_sec", label: "import & 기초" },
      { id: "create", label: "배열 생성" },
      { id: "shape", label: "shape & 변환" },
      { id: "index", label: "인덱싱" },
      { id: "math", label: "수학 연산" },
      { id: "stat", label: "통계 & 정렬" },
      { id: "linalg", label: "선형대수" },
      { id: "random", label: "난수" },
      { id: "utils", label: "유틸 & 기타" },
    ],
  },
  {
    slug: "pandas",
    title: "Pandas",
    description: "DataFrame · 필터링 · groupby · 병합 · I/O",
    icon: "⊞",
    color: "#5B8DB8",
    category: "ml",
    sections: [
      { id: "import_sec", label: "import & 기초" },
      { id: "struct", label: "자료구조" },
      { id: "select", label: "선택 & 인덱싱" },
      { id: "filter", label: "필터링 & 정렬" },
      { id: "clean", label: "결측값 & 정제" },
      { id: "transform", label: "변환 & 연산" },
      { id: "groupby", label: "groupby & 집계" },
      { id: "merge", label: "병합 & 연결" },
      { id: "io", label: "파일 입출력" },
      { id: "stat", label: "통계 & 시각화" },
      { id: "adv_prep", label: "전처리 심화" },
    ],
  },
  {
    slug: "matplotlib",
    title: "Matplotlib",
    description: "기본 플롯 · 통계 · 레이아웃 · 3D",
    icon: "◈",
    color: "#5C9E6E",
    category: "ml",
    sections: [
      { id: "import_sec", label: "import & 기초" },
      { id: "figure", label: "Figure & Axes" },
      { id: "plot2d", label: "기본 플롯" },
      { id: "stat_plot", label: "통계 플롯" },
      { id: "styling", label: "스타일링" },
      { id: "layout", label: "레이아웃" },
      { id: "text", label: "텍스트 & 주석" },
      { id: "save", label: "저장 & 출력" },
      { id: "plot3d", label: "3D 시각화" },
    ],
  },
  {
    slug: "scipy",
    title: "SciPy",
    description: "확률분포 · 가설검정 · 최적화 · FFT",
    icon: "∫",
    color: "#8B6BB1",
    category: "ml",
    sections: [
      { id: "import_sec", label: "import & 개요" },
      { id: "dist", label: "확률분포" },
      { id: "hypo", label: "가설검정" },
      { id: "corr", label: "상관 & 비모수" },
      { id: "optim", label: "최적화 & 커브피팅" },
      { id: "spatial", label: "거리 & 공간" },
      { id: "integrate", label: "적분 & 미분방정식" },
      { id: "interpolate", label: "보간법" },
      { id: "ndimage", label: "이미지 처리" },
      { id: "fft_sec", label: "푸리에 변환" },
      { id: "stats_adv", label: "변환 & 심화" },
    ],
  },
  {
    slug: "sklearn",
    title: "Scikit-learn",
    description: "전처리 · 선형/트리 모델 · 평가 · Pipeline",
    icon: "⚙",
    color: "#E07040",
    category: "ml",
    sections: [
      { id: "import_sec", label: "import & API 구조" },
      { id: "preprocess", label: "전처리" },
      { id: "linear", label: "선형 모델" },
      { id: "tree", label: "트리 & 앙상블" },
      { id: "svm_knn", label: "SVM & KNN" },
      { id: "cluster", label: "클러스터링" },
      { id: "dim_red", label: "차원 축소" },
      { id: "eval", label: "검증 & 평가지표" },
      { id: "pipeline", label: "Pipeline & 튜닝" },
    ],
  },
  {
    slug: "statsmodels",
    title: "Statsmodels",
    description: "OLS · GLM · ARIMA · 가설검정",
    icon: "~",
    color: "#C0602A",
    category: "ml",
    sections: [
      { id: "import_sec", label: "import & 개요" },
      { id: "ols", label: "OLS 선형회귀" },
      { id: "glm", label: "GLM & 로지스틱" },
      { id: "ts_basic", label: "시계열 기초" },
      { id: "arima", label: "ARIMA & SARIMA" },
      { id: "test", label: "가설검정" },
      { id: "smoothing", label: "지수평활법" },
    ],
  },
  {
    slug: "xgboost",
    title: "XGBoost",
    description: "sklearn API · Native API · 파라미터 · 튜닝",
    icon: "⊕",
    color: "#B8860B",
    category: "ml",
    sections: [
      { id: "import_sec", label: "import & 개요" },
      { id: "sklearn_api", label: "sklearn API" },
      { id: "native_api", label: "Native API" },
      { id: "params", label: "핵심 파라미터" },
      { id: "interpret", label: "특성 중요도" },
      { id: "tuning", label: "튜닝 전략" },
    ],
  },
  {
    slug: "crawling",
    title: "Crawling & DB",
    description: "requests · BeautifulSoup · pymysql · DuckDB · 금융",
    icon: "⊗",
    color: "#4A8FA8",
    category: "ml",
    sections: [
      { id: "import_sec", label: "Import 패턴" },
      { id: "requests_sec", label: "requests & BS4" },
      { id: "pymysql_sec", label: "pymysql / SQLAlchemy" },
      { id: "duckdb_sec", label: "DuckDB" },
      { id: "finance_sec", label: "FinanceDataReader" },
    ],
  },
  {
    slug: "naive_bayes",
    title: "Naive Bayes",
    description:
      "Bayes 원리 · CategoricalNB · BernoulliNB · MultinomialNB · 튜닝",
    icon: "ℙ",
    color: "#2E86AB",
    category: "ml",
    sections: [
      { id: "nb_intro", label: "Bayes 원리 & 개요" },
      { id: "categorical_nb", label: "CategoricalNB" },
      { id: "bernoulli_nb", label: "BernoulliNB" },
      { id: "multinomial_nb", label: "MultinomialNB" },
      { id: "nb_tuning", label: "튜닝 & 서비스 함수" },
      { id: "nb_eval", label: "평가 & 시각화" },
    ],
  },
  {
    slug: "ml_classification",
    title: "ML Classification",
    description: "확률기초 · MLE · 로지스틱 · 임계값 · 평가 · PCA",
    icon: "σ",
    color: "#9B59B6",
    category: "ml",
    sections: [
      { id: "prob", label: "확률 기초" },
      { id: "likelihood", label: "우도 & MLE" },
      { id: "logistic", label: "로지스틱 회귀" },
      { id: "threshold", label: "임계값 분석" },
      { id: "evaluation", label: "모델 평가" },
      { id: "pca", label: "PCA 차원축소" },
    ],
  },
  {
    slug: "knn_kmeans",
    title: "KNN & KMeans",
    description: "K-최근접 이웃 · 군집화 · 이상치 탐지 · DBSCAN",
    icon: "K",
    color: "#0ea5e9",
    category: "ml",
    sections: [
      { id: "nearest_neighbors", label: "NearestNeighbors 기초" },
      { id: "knn_classifier", label: "KNN 분류 / 회귀" },
      { id: "knn_advanced", label: "KNN 응용" },
      { id: "lof", label: "LOF 이상치 탐지" },
      { id: "kmeans", label: "KMeans 군집화" },
      { id: "kmeans_eval", label: "군집 평가" },
      { id: "kmeans_advanced", label: "KMeans 응용" },
      { id: "hierarchical", label: "계층적 군집화" },
      { id: "dbscan", label: "DBSCAN" },
    ],
  },
  {
    slug: "dim_reduction",
    title: "Dimensionality Reduction",
    description: "SVD · PCA · IncrementalPCA · KernelPCA · UMAP · Manifold",
    icon: "⊕",
    color: "#7c3aed",
    category: "ml",
    sections: [
      { id: "svd", label: "SVD" },
      { id: "pca_core", label: "PCA 핵심" },
      { id: "pca_variants", label: "PCA 변형" },
      { id: "manifold", label: "매니폴드" },
    ],
  },
  {
    slug: "svm",
    title: "SVM",
    description: "SVC · 커널 함수 · NuSVC · Platt Scaling · 이상탐지",
    icon: "⊕",
    color: "#7c3aed",
    category: "ml",
    sections: [
      { id: "svc_basics", label: "SVC 기초" },
      { id: "kernel_types", label: "커널 함수" },
      { id: "nusvc_params", label: "NuSVC 파라미터" },
      { id: "multiclass", label: "다중분류" },
      { id: "platt_scaling", label: "Platt Scaling" },
      { id: "oneclass_svm", label: "이상탐지" },
    ],
  },
  {
    slug: "text_mining",
    title: "Text Mining",
    description: "One-Hot · TF-IDF · NLTK · Gensim · Word2Vec · KoNLPy",
    icon: "言",
    color: "#7c3aed",
    category: "ml",
    sections: [
      { id: "encoding", label: "Encoding & TF-IDF" },
      { id: "nltk_basic", label: "NLTK 토크나이징" },
      { id: "nltk_classify", label: "NLTK 분류" },
      { id: "gensim_dict", label: "Gensim Dictionary" },
      { id: "gensim_topic", label: "LSI 토픽 모델링" },
      { id: "gensim_word2vec", label: "Word2Vec / FastText" },
      { id: "korean_nlp", label: "KoNLPy · WordCloud" },
    ],
  },
  {
    slug: "ann",
    title: "ANN / MLP",
    description:
      "MLPClassifier · MLPRegressor · 손실함수 · 활성화함수 · 임계값 최적화",
    icon: "🧠",
    color: "#7c3aed",
    category: "ml",
    sections: [
      { id: "mlp_basic", label: "MLP 기본 구조" },
      { id: "loss_functions", label: "손실함수" },
      { id: "activation_functions", label: "활성화함수" },
      { id: "training_tuning", label: "학습 튜닝" },
      { id: "threshold_calibration", label: "임계값 최적화" },
    ],
  },
  {
    slug: "tensorflow_ffnn",
    title: "TensorFlow / FFNN",
    description:
      "텐서 기초 · 선형대수 · GradientTape · Dense/Sequential · 커스텀 모델 · MNIST 학습",
    icon: "⚡",
    color: "#f97316",
    category: "dl",
    sections: [
      { id: "tensor_basics", label: "텐서 기초" },
      { id: "linear_algebra", label: "선형대수" },
      { id: "tensor_shape_ops", label: "텐서 변형" },
      { id: "dense_bias", label: "Dense / Bias" },
      { id: "autodiff_training", label: "자동미분 · 학습루프" },
      { id: "keras_sequential_mode", label: "Sequential · 그래프모드" },
      { id: "loss_and_custom_model", label: "손실함수 · 커스텀 모델" },
    ],
  },
  {
    slug: "cnn",
    title: "CNN / Grad-CAM",
    description:
      "Conv2D · MaxPooling · Grad-CAM 시각화 · 데이터 증강 · tf.data",
    icon: "▦",
    color: "#f97316",
    category: "dl",
    sections: [
      { id: "conv_basics", label: "Conv2D / Pooling 기초" },
      { id: "train_eval", label: "모델 학습 & 평가" },
      { id: "gradcam", label: "Grad-CAM 시각화" },
      { id: "augmentation", label: "데이터 증강" },
      { id: "tf_data_tfds", label: "tf.data & TFDS" },
    ],
  },
  {
    slug: "transfer_learning",
    title: "Transfer Learning",
    description:
      "전이학습 전략 · Xception · EfficientNet · 커스텀 파이프라인 · 튜닝",
    icon: "⇄",
    color: "#f97316",
    category: "dl",
    sections: [
      { id: "tl_concept", label: "전이학습 개념 & 전략" },
      { id: "feature_extraction", label: "Feature Extraction (Xception)" },
      { id: "efficientnet", label: "EfficientNet 계열" },
      { id: "custom_pipeline", label: "커스텀 이미지 파이프라인" },
      { id: "hp_tuning", label: "하이퍼파라미터 튜닝" },
    ],
  },
];

export function getLibrary(slug: string): Library | undefined {
  return LIBRARIES.find((l) => l.slug === slug);
}

export const CATEGORY_LABELS: Record<LibCategory, string> = {
  ml: "머신러닝",
  dl: "딥러닝",
};
